export const Utils = {
  CHART_COLORS: {
    red: 'rgb(255, 99, 132)',
    orange: 'rgb(255, 159, 64)',
    yellow: 'rgb(255, 205, 86)',
    green: 'rgb(136, 206, 70)',
    blue: 'rgb(54, 162, 235)',
    purple: 'rgb(153, 102, 255)',
    grey: 'rgb(201, 203, 207)'
  },
}

export const headerMap = {
  centro_solic: "Centro Solicitante",
  str_projeto: "Aeronave",
  projeto: "Projeto",
  str_ns: "Número de série",
  tipo_orig: "Tipo",
  str_ordem: "Ordem",
  cemb_mat_falt: "Material",
  pn_mat_falt: "Part Number",
  descr_mat_falt: "Descrição",
  qtd_falt: "Quantidade de faltas",
  dat_limite: "Data limite",
  status_falta: "Status",
  dat_przo: "Prazo",
  cont_prz: "Contagem",
  efet_prev_man: "Efetivas/Preventivas",
  centro_forn: "Centro fornecedor",
  ppcp_forn: "PPCP Fornecedor",
  area: "Area",
  apoio: "Apoio",
  ppcp_solic: "PPCP Solicitante",
  comn_solic: "Comentário Solicitante",
  str_imp_doc: "Documento",
  str_tipo_doc: "Tipo de documento",
  str_imp_po: "Número PO",
  num_imp_linha: "Linha PO",
  str_imp_obs: "Observação",
  str_programa: "Programa",
  str_tipo_ordem: "Tipo de Ordem",
  str_status_sap: "Status SAP",
  str_pos_montagem: "Posição de montagem",
  str_pos_atual: "Posição atual",
  data_real_inicio: "Data de início",
  str_elemento_pep: "Elemento PEP",
  data_pipo: "Data PIPO",
  rank_prioridade: "Rank Prioridade",

  str_nome: "Nome",
  str_pn: "Part Number",
  str_cemb: "CEMB",
  str_descricao: "Descrição",

  num_qtd_falt_pgto: "Qtd. Falta Pgto",
  str_umb: "Un. Medida",
  num_qtd_stk_gpx: "Estoque GPX",
  num_qtd_stk_bot: "Estoque BOT",
  num_qtd_stk_eug: "Estoque EUG",
  num_qtd_stk_sjk: "Estoque SJK",
  num_qtd_stk_tte: "Estoque TTE",
  num_qtd_stk_vcp: "Estoque VCP",

  possui_stk_pep: "Possui Estoque PEP",
  flag_lid: "LID",
  data_pagamento_programado: "Data Pgto Programado",
};
